### ISSUE TITLE
Missing prepare_datasets/resize_crop.py

### ISSUE THREAD

**Issue by yifeiwang77** [xuwangyin/AT-EBMs#1]
Hi Xuwang,

Congratulations on your exciting work! I find it is a very natural way to apply AT to EBMs (a discriminator is all you need!), and I cannot wait to try it out. 

Nevertheless, I find the ``resize_crop.py`` file is missing, which causes errrors when running ``create_celebahq256.sh``.

Looking forward to your reply!

**Comment by xuwangyin** [comment]
Thank you for your interest and raising the issue. I have uploaded the missing file.
