### ISSUE TITLE
The connection between AT and EBM is firstly drawn by CEM

### ISSUE THREAD

**Issue by yifeiwang77** [xuwangyin/AT-EBMs#2]
In [our ICLR 2022 paper A Unified Contrastive Energy-based Model for Understanding the Generative Ability of Adversarial Training (CEM)](http://arxiv.org/pdf/2203.13455), we are the first to point out the inherent connection between adversarial attack and Langevin sampling. Based on that, we firstly interpreted AT as a method to train EBMs, and demonstrate the superiority of AT compared to CD. Therefore, we believe that your proposed AT-EBM is highly correlated to ours, and it would be better if you could elaborate their connections and differences in the paper.

**Comment by xuwangyin** [comment]
Hi Yifei,

I appreciate your feedback. I will include a discussion when I update the paper on arXiv. 

Thank you.

**Comment by xuwangyin** [comment]
Hi Yifei, I am planning to include the following discussion in the updated version. Could you please help whether the description of your work is accurate? Thank you.

> Our work is related to~\cite{wang2022a} which is also an attempt to understand and improve AT's generative capability. The authors' focus is on the supervised setting, where they make a connection between the standard multiclass AT and the Contrastive Energy-based Model (CEM) proposed by the authors. Our analysis is in an unsupervised setting, where we connect binary AT with the standard EBMs formulation. Although~\cite{wang2022a} also considers the unsupervised scenario, their generative model is a contrastive learning model~\cite{jiang2020robust} which requires training samples to perform test time sampling. Our generative model is based on binary AT and follows the standard practice of MCMC sampling from the learned energy function.

**Comment by xuwangyin** [comment]
> In [our ICLR 2022 paper A Unified Contrastive Energy-based Model for Understanding the Generative Ability of Adversarial Training (CEM)](http://arxiv.org/pdf/2203.13455), we are the first to point out the inherent connection between adversarial attack and Langevin sampling. Based on that, we firstly interpreted AT as a method to train EBMs, and demonstrate the superiority of AT compared to CD. Therefore, we believe that your proposed AT-EBM is highly correlated to ours, and it would be better if you could elaborate their connections and differences in the paper.

Hi Yifei, I am planning to include the following discussion in the updated version. Could you please help check whether the description of your work is accurate? Thank you.

> Our work is related to~\cite{wang2022a} which is also an attempt to understand and improve AT's generative capability. The authors' focus is on the supervised setting, where they make a connection between the standard multiclass AT and the Contrastive Energy-based Model (CEM) proposed by the authors. Our analysis is in an unsupervised setting, where we connect binary AT with the standard EBMs formulation. Although~\cite{wang2022a} also considers the unsupervised scenario, their generative model is a contrastive learning model~\cite{jiang2020robust} which requires training samples to perform test time sampling. Our generative model is based on binary AT and follows the standard practice of MCMC sampling from the learned energy function.

**Comment by yifeiwang77** [comment]
The revision seems fine to me. Thanks!

**Comment by yifeiwang77** [comment]
I am sorry to mention one piece in your discussion that I previously overlooked. In fact, CEM does NOT require training samples to perform test time sampling (which would be less useful). Instead, in our sampling algorithm, it draws a batch of test samples from random initialization, and then update the batch of test samples together with intra-batch contrast.
